# Projet 2 - Participez à un concours sur la Smart City

Etudiant : *David Scanu* - [Parcours "AI Engineer"](https://openclassrooms.com/fr/paths/795-ai-engineer)

Réaliser une **analyse exploratoire** avec un jeu de données portant sur les arbres de la ville de Paris, dans le cadre du programme “Végétalisons la ville”.

Vos résultats contribueront à une optimisation des tournées pour l’entretien des arbres de la ville.

---


## Sommaire
- Importation
- Visualisation
- Valeurs manquantes
- Outliers
- Doublons





## 👀 Visualisation générale du jeu de données

In [440]:
data_filepath = "data/p2-arbres-fr.csv"

In [441]:
import pandas as pd

data = pd.read_csv(data_filepath, delimiter=";")

In [442]:
data.shape
print(f"Le DataFrame de notre jeu de données contient : \n - {data.shape[0]} lignes \n - {data.shape[1]} colonnes.")

Le DataFrame de notre jeu de données contient : 
 - 200137 lignes 
 - 18 colonnes.


In [444]:
# Visualisation d'un échantillon des données
data.head(50)

id type_emplacement domanialite   arrondissement complement_addresse  \
0   99874            Arbre      Jardin   PARIS 7E ARRDT                 NaN   
1   99875            Arbre      Jardin   PARIS 7E ARRDT                 NaN   
2   99876            Arbre      Jardin   PARIS 7E ARRDT                 NaN   
3   99877            Arbre      Jardin   PARIS 7E ARRDT                 NaN   
4   99878            Arbre      Jardin  PARIS 17E ARRDT                 NaN   
5   99879            Arbre      Jardin  PARIS 17E ARRDT                 NaN   
6   99880            Arbre      Jardin  PARIS 17E ARRDT                 NaN   
7   99881            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
8   99882            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
9   99883            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
10  99884            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
11  99885            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
12  99887            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
13  99888            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
14  99889            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
15  99890            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
16  99891            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
17  99892            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
18  99893            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
19  99894            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
20  99895            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
21  99896            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
22  99897            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
23  99898            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
24  99899            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
25  99900            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
26  99901            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
27  99902            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
28  99903            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
29  99904            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
30  99905            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
31  99907            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
32  99909            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
33  99910            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
34  99911            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
35  99912            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
36  99913            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
37  99914            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
38  99915            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
39  99916            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
40  99917            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
41  99918            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
42  99919            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
43  99920            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
44  99922            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
45  99923            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
46  99924            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
47  99925            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
48  99926            Arbre      Jardin  PARIS 16E ARRDT                 NaN   
49  99927            Arbre      Jardin  PARIS 16E ARRDT  

## Type de données

- Nature des variables : 
  - quantitatives (discrètes, continues)
  - qualitatives (nomiales, oridnales)


In [445]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200137 entries, 0 to 200136
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   id                   200137 non-null  int64  
 1   type_emplacement     200137 non-null  object 
 2   domanialite          200136 non-null  object 
 3   arrondissement       200137 non-null  object 
 4   complement_addresse  30902 non-null   object 
 5   numero               0 non-null       float64
 6   lieu                 200137 non-null  object 
 7   id_emplacement       200137 non-null  object 
 8   libelle_francais     198640 non-null  object 
 9   genre                200121 non-null  object 
 10  espece               198385 non-null  object 
 11  variete              36777 non-null   object 
 12  circonference_cm     200137 non-null  int64  
 13  hauteur_m            200137 non-null  int64  
 14  stade_developpement  132932 non-null  object 
 15  remarquable      

### Variables qualitatives

- id
- type_emplacement
- domanialite
- arrondissement
- complement_addresse
- numéro
- lieu
- id_emplacement
- libelle_francais
- genre 
- espece
- variete
- stade_developpement
- remarquable (bool)

Bien qu'elles soient des **valeurs numériques**, les variables suivantes sont qualitatives : 

- La variable `id` est une variable **qualitative nominale**. 
- La variable `remarquable` est une variable **qualitative ordinale**, car elle ne contient que deux valeurs 0 et 1 (valeurs booléennes). 

In [411]:
# Montrer la description pour chaque variable qualitative

for col in data.columns:
    if data[col].dtypes in ['object', 'bool']: 
        print("Nom de colonne : ", col)
        print(data[col].describe())
        print()
        print(data[col].unique())
        print("---")
        print()

Nom de colonne :  type_emplacement


count     200137
unique         1
top        Arbre
freq      200137
Name: type_emplacement, dtype: object

['Arbre']
---

Nom de colonne :  domanialite
count         200136
unique             9
top       Alignement
freq          104949
Name: domanialite, dtype: object

['Jardin' 'Alignement' 'DJS' 'DFPE' 'CIMETIERE' 'DASCO' 'DAC'
 'PERIPHERIQUE' 'DASES' nan]
---

Nom de colonne :  arrondissement
count              200137
unique                 25
top       PARIS 15E ARRDT
freq                17151
Name: arrondissement, dtype: object

['PARIS 7E ARRDT' 'PARIS 17E ARRDT' 'PARIS 16E ARRDT' 'PARIS 4E ARRDT'
 'PARIS 13E ARRDT' 'PARIS 12E ARRDT' 'PARIS 19E ARRDT' 'PARIS 14E ARRDT'
 'PARIS 15E ARRDT' 'PARIS 3E ARRDT' 'PARIS 20E ARRDT' 'PARIS 18E ARRDT'
 'PARIS 6E ARRDT' 'PARIS 11E ARRDT' 'PARIS 1ER ARRDT' 'PARIS 2E ARRDT'
 'PARIS 5E ARRDT' 'VAL-DE-MARNE' 'SEINE-SAINT-DENIS' 'HAUTS-DE-SEINE'
 'PARIS 9E ARRDT' 'PARIS 10E ARRDT' 'PARIS 8E ARRDT' 'BOIS DE BOULOGNE'
 'BOIS DE VINCENNES']
---

Nom 

### Variable quantitatives

- circonference_cm
- hauteur_m
- geo_point_2d_a
- geo_point_2d_b

## Nettoyages des données

- valeurs manquantes NaN
- Doublons
- Erreur lexicales
- erreur d'irrégularité
- date ? 
- outliers (valeurs aberrantes)

### Traitement de données manquantes

- Oubliez une variable
- Oubliez des individus
- Imputation

In [412]:
# Afficher les valeurs manquantes pour chaque colonne 
print(data.isna().sum())

id                          0
type_emplacement            0
domanialite                 1
arrondissement              0
complement_addresse    169235
numero                 200137
lieu                        0
id_emplacement              0
libelle_francais         1497
genre                      16
espece                   1752
variete                163360
circonference_cm            0
hauteur_m                   0
stade_developpement     67205
remarquable             63098
geo_point_2d_a              0
geo_point_2d_b              0
dtype: int64


#### Supprimer les colonnes contenant uniquement des valeurs manquantes


La variable `numero` est **toujours vide**. Cette colonne peut être **supprimée**.

In [413]:
data.drop(columns=['numero'], inplace=True) 

#### Supprimer les individus contenant des valeurs manquantes

Les nans sont peu nombreux pour les colonnes suivantes. Nous décidons de supprimer les individus dont ces colonnes contiennent des Nans.
- libelle_francais : **faire un tournée pour obtenir l'information et remplir ce champs**
- genre
- espece

In [414]:
# data.dropna(subset=['libelle_francais', 'genre', 'espece'], inplace=True) 
# data.shape

(197253, 17)

`stade_developpement`


Que faire ?  Nan = 'Inconnu'

In [415]:
data ['stade_developpement'].unique()

array([nan, 'A', 'J', 'M', 'JA'], dtype=object)

In [416]:
data['stade_developpement'].isna().sum()

np.int64(66224)

In [417]:
data["stade_developpement"].value_counts()

stade_developpement
A     63693
JA    34828
J     26411
M      6097
Name: count, dtype: int64

In [446]:
# Remplacer Nan par une nouvelle modalité : 'inconnu'

### Nettoyage divers

#### Suppression `type_emplacement`

`type_emplacement` ne contient qu'une seule catégorie **Arbre**. Elle peut donc être supprimée.

In [449]:
data['type_emplacement'].unique()

array(['Arbre'], dtype=object)

In [423]:
data.drop('type_emplacement', axis=1, inplace=True)

#### Convertir `remarquable` en type booléen

- NaN : non remarquable (imputation "métier" ou "fonctionnelle")
- 'remarquable' peut nous servir pour organiser une tournée particulière d'une équipe d'entretien.

In [419]:
# remarquable
data['remarquable'].unique()

array([ 0., nan,  1.])

In [448]:
# Convertion en booléen (converti les NaNs en False)
data['remarquable'] = data['remarquable'].astype('bool')

In [421]:
data['remarquable'].unique()

array([False,  True])

In [ ]:
data['remarquable'].unique()

#### Nettoyer `variete`

Il y a une `'` dans les variétés

In [424]:
data['variete'].unique()

array([nan, "Atropunicea'", "Euchlora'", "Schwedleri'", "Pissardii'",
       "Pallida'", 'n. sp.', "Chanticleer'", "Purpureum'", "Italica'",
       "Aspleniifolia'", "Jacquemontii'", "Fastigiata'",
       "Fastigiate Koster'", "Imperialis'", "Honey Dew'",
       "Jacqueline Hillier'", "Rubra Plena'", "Diversifolia'",
       "Flamingo'", "Argentea Marginata'", "Pendula'", "Liempde'",
       "Pyramidalis'", "Tortuosa'", "Aurea'", "Frisia'", "Leopoldii'",
       "Briotii'", "Kanzan'", "Variegata'", "Hizakura'", "Albomarginata'",
       "Bradford'", "Autumnalis Rosea'", "Atropurpurea'",
       "Castanaefolia'", "Autumnalis'", "Heaven Scent'", "Schouten'",
       "Sundew'", "Leonard messel'", "Merrill'", "Plena'", "Unifolia'",
       "Baumannii'", "Virginiana'", "Flying Dragon'", "Laciniata'",
       "Laciniatum'", "Globosum'", "Rohanii'", "Glauca'", "Youngii'",
       "Contorta'", "Umbraculifera'", "Jaspidea'", "Spaeth'", "Flekova'",
       "Regent'", "Atrovirens'", "Purpurea'", "Alba'",
 

In [425]:
data['variete'] = data['variete'].str.replace("'", '') # supprimer ' dans les valeurs
data['variete'] = data['variete'].str.strip() # nettoie les espace avant et après

In [426]:
data['variete'].unique()

array([nan, 'Atropunicea', 'Euchlora', 'Schwedleri', 'Pissardii',
       'Pallida', 'n. sp.', 'Chanticleer', 'Purpureum', 'Italica',
       'Aspleniifolia', 'Jacquemontii', 'Fastigiata', 'Fastigiate Koster',
       'Imperialis', 'Honey Dew', 'Jacqueline Hillier', 'Rubra Plena',
       'Diversifolia', 'Flamingo', 'Argentea Marginata', 'Pendula',
       'Liempde', 'Pyramidalis', 'Tortuosa', 'Aurea', 'Frisia',
       'Leopoldii', 'Briotii', 'Kanzan', 'Variegata', 'Hizakura',
       'Albomarginata', 'Bradford', 'Autumnalis Rosea', 'Atropurpurea',
       'Castanaefolia', 'Autumnalis', 'Heaven Scent', 'Schouten',
       'Sundew', 'Leonard messel', 'Merrill', 'Plena', 'Unifolia',
       'Baumannii', 'Virginiana', 'Flying Dragon', 'Laciniata',
       'Laciniatum', 'Globosum', 'Rohanii', 'Glauca', 'Youngii',
       'Contorta', 'Umbraculifera', 'Jaspidea', 'Spaeth', 'Flekova',
       'Regent', 'Atrovirens', 'Purpurea', 'Alba', 'Pauls Scarlet Hamlet',
       'Lutea', 'Dawyck', 'Totem', 'Erythrocl

### Outliers

- une valeur aberrante : c'est une valeur qui est manifestement fausse
- une valeur atypique : c'est une valeur qui "sort du lot", mais pas forcément fausse.


##### Les plus grands arbres de Paris

> Le plus grand : le Séquoia des Buttes-Chaumont : D’une circonférence de 4,70 m et d’une hauteur de plus de 35 mètres


> Le plus gros : platane d’Orient du Parc Monceau : son tronc mesure en effet 7 mètres de circonférence pour une hauteur de 31 mètres environ !

Source  : https://www.unjourdeplusaparis.com/paris-vert/arbres-remarquables-paris

In [428]:
data[['circonference_cm', 'hauteur_m', 'geo_point_2d_a', 'geo_point_2d_b']].describe()

circonference_cm      hauteur_m  geo_point_2d_a  geo_point_2d_b
count     197253.000000  197253.000000   197253.000000   197253.000000
mean          83.866790      13.214476       48.854426        2.348045
std          678.044755    1985.575302        0.030231        0.051249
min            0.000000       0.000000       48.742290        2.210241
25%           30.000000       5.000000       48.835014        2.307313
50%           70.000000       8.000000       48.854096        2.350886
75%          115.000000      12.000000       48.876337        2.386702
max       250255.000000  881818.000000       48.911485        2.469759

#### `hauteur_m`

Valeurs abérrantes :
- hauteur 0 m : est-ce qu'on considère que ce sont des arbres dont la hauteur est inférieure à 1 m (par ex, graines) ? Aller vérifier sur Google maps. 
- hauteur supérieure à 35 m.

Identifier : 
- Diagramme de distribution (**Box plot**)
- Visualisez l'arbre sur Google Maps (pourconforter l'analyse)

Traitement : 
- Modifier à la main en changeant la décimale pour les valeurs supérieures à 1000 
- Moyenne de hauteur des arbres à proximité et appliquer la moyenne (gorupée par zone)
- Partie recommandation : Réaliser un tournée de mesure de ces arbres

In [453]:
# hauteur_m : minimum
print(f"{data[data['hauteur_m'] == 0]['hauteur_m'].count()} arbres ont la hauteur de 0 m.")

39219 arbres ont la hauteur de 0 m.


In [435]:
# # convertir en float
# data = data.astype({'hauteur_m': 'float'})
# # Remplacer les zéros par la moyenne par la moyenne
# data.loc[data['hauteur_m'].isnull(), 'hauteur_m'] = data['hauteur_m'].mean()

In [452]:
# hauteur_m : maximum
print(f"{data[data['hauteur_m'] > 35]['hauteur_m'].count()} arbres ont une hauteur supérieure à 35 m.")

509 arbres ont une hauteur supérieure à 35 m.


In [430]:
# data.drop(data[data['hauteur_m'] > 35].index, inplace=True)

In [454]:
data['hauteur_m'].describe()

count    200137.000000
mean         13.110509
std        1971.217387
min           0.000000
25%           5.000000
50%           8.000000
75%          12.000000
max      881818.000000
Name: hauteur_m, dtype: float64

#### `circonference_cm`

Valeurs abérrantes :
- circonférence de 0
- circonférence supérieure à 750 cm

In [455]:
# 
print(f"{data[data['circonference_cm'] == 0]['hauteur_m'].count()} arbres ont la circonférence de 0 cm.")

25867 arbres ont la circonférence de 0 cm.


In [457]:
circ_max = 750
print(f"{data[data['circonference_cm'] > circ_max]['circonference_cm'].count()} arbres ont une circonférence supérieure à {circ_max} cm.")

81 arbres ont une circonférence supérieure à 750 cm.


In [ ]:
# Suppression des individus dont la circonférence est supérieure à 
data.drop(data[data['circonference_cm'] > 750].index, inplace=True)

### Doublons

In [64]:
data.shape[0]

200137

In [62]:
data['id'].unique().size

200137

In [66]:
data.loc[data['id'].duplicated(keep=False),:]

Empty DataFrame
Columns: [id, type_emplacement, domanialite, arrondissement, complement_addresse, numero, lieu, id_emplacement, libelle_francais, genre, espece, variete, circonference_cm, hauteur_m, stade_developpement, remarquable, geo_point_2d_a, geo_point_2d_b]
Index: []

Il n'y a pas de doublons dans notre jeu de données.

## Distribution empirique